# Generated by Django 4.0.2 on 2022-02-20 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0002_detailseconds'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Detailseconds',
        ),
    ]
